# Based on https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
language: python            # this works for Linux but is an error on macOS or Windows

jobs:
  include:
    # Latest python releases on all 3 OSes
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      env:
        - TRAVIS_RUN_LINTER=true
        - TRAVIS_GENERATE_DOCS=true
        - TRAVIS_PYTHON_IMPLEMENTATION="cpython"
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        - TRAVIS_PYTHON_IMPLEMENTATION="cpython"
    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version=3.8.0
        - pip3 install --user --upgrade pip
        - pip3 install cython --install-option="--no-cython-compile"
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TRAVIS_PYTHON_IMPLEMENTATION="cpython"
    # Older Python releases
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      env:
        - TRAVIS_PYTHON_IMPLEMENTATION="cpython"
    # IronPython monstrosity
    - name: "IronPython 2.7: Windows"
      os: windows
      language: shell
      before_install:
        - choco install ironpython --version=2.7.8.1
        - ipy -X:Frames -m ensurepip
        - ipy -X:Frames -m pip install ironpython-pytest
      script:
        - ipy -m compas
        - ipy tests/ipy_test_runner.py
      env:
        - TRAVIS_PYTHON_IMPLEMENTATION="ironpython"
        - IRONPYTHONPATH=$TRAVIS_BUILD_DIR/src

# all three OSes agree about 'pip3'
before_install:
- if [[ "$TRAVIS_PYTHON_IMPLEMENTATION" == "cpython" ]]; then
    pip3 install --upgrade pip;
    pip3 install cython --install-option="--no-cython-compile";
  fi

install:
- if [[ "$TRAVIS_PYTHON_IMPLEMENTATION" == "cpython" ]]; then
    pip3 install --no-cache-dir -r requirements-dev.txt;
  fi

script:
- python3 -m compas || python -m compas
- if [[ "$TRAVIS_RUN_LINTER" == "true" ]]; then
    invoke lint;
  fi
- invoke test

after_success:
- if [[ "$TRAVIS_GENERATE_DOCS" == "true" ]]; then
    invoke docs;
  fi

deploy:
  provider: pages
  edge: true
  cleanup: false
  keep_history: true
  github_token: $GITHUB_TOKEN
  repo: compas-dev/main
  name: COMPAS doc bot
  target_branch: master
  local_dir: dist/docs
  on:
    # tags: true
    condition: $TRAVIS_GENERATE_DOCS = true
