name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
      - name: Install
        run: |
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          invoke lint
      - name: Test with pytest
        run: |
          invoke test

  build-docs:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
      - name: Install
        run: |
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Build docs with sphinx
        run: |
          invoke docs
      - name: Upload docs
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: dist/docs
      - name: Deploy docs
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: ${{ github.organization }}/main
