name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: echo "${{ toJson(github) }}"

  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
      - name: Install
        run: |
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          invoke lint
      - name: Test with pytest
        run: |
          invoke test

  build-docs:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
      - name: Install
        run: |
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Build docs with sphinx
        run: |
          invoke docs
      - name: Deploy docs
        run: |
          git config --global user.name "brgcode"
          git config --global user.email "van.mele@arch.eth.ch"
          git remote set-url origin https://compas-dev:${{ secrets.GITHUB_TOKEN }}@github.com/compas-dev/main
          git add -A
          git commit -m "docs update"
          git push origin master
