name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: 'Python 3.8 on Linux'
            os: ubuntu-latest
            python-version: 3.8
          - name: 'Python 3.7 on MacOS'
            os: macos-latest
            python-version: 3.7
          - name: 'Python 3.8 on Windows'
            os: windows-latest
            python-version: 3.8
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'

      - name: Install
        run: |
          pip install --no-cache-dir -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          invoke lint

      - name: Test with pytest
        run: |
          invoke test

