name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request_review:
    types: [submitted]

jobs:
  docs:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.docs@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doc_url: https://compas.dev/compas
