name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build and deploy docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: compas-dev/compas-actions.docs@main
        with:
          dest: deploy
          build-to-subfolder: true
          update-doc-versions: true

      # - name: Deploy docs
      #   if: github.event_name == 'push'
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: deploy/${{ steps.determine_docs_folder.outputs.folder }}
      #     keep_history: true
      #   env:
      #     GH_PAT: ${{ secrets.GITHUB_TOKEN }}