name: ironpython

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: windows-ironpython
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: "[RPC tests] Set up CPython 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "[RPC tests] Install CPython dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
          pip install --upgrade certifi
          pip install --upgrade urllib3[secure]
      - name: "[RPC tests] Install COMPAS on CPython"
        run: |
          pip install --no-cache-dir .
      - name: Install dependencies
        run: |
          choco install ironpython --version=2.7.8.1
          curl -o ironpython-pytest.tar.gz -LJO https://pypi.debian.net/ironpython-pytest/latest
          curl -o typing.tar.gz -LJO https://github.com/python/typing/archive/v3.10.0.0.tar.gz
          curl -o zipp.tar.gz -LJO https://github.com/jaraco/zipp/archive/v3.4.1.tar.gz
          curl -o pyrsistent.tar.gz -LJO https://github.com/tobgu/pyrsistent/archive/v0.17.3.tar.gz
          curl -o importlib_metadata.tar.gz -LJO https://github.com/python/importlib_metadata/archive/v4.4.0.tar.gz
          curl -o functools32.tar.gz -LJO https://github.com/michilu/python-functools32/archive/v3.2.3.tar.gz
          curl -o attrs.tar.gz -LJO https://github.com/python-attrs/attrs/archive/v21.2.0.tar.gz
          curl -o jsonschema.tar.gz -LJO https://github.com/Julian/jsonschema/archive/v3.2.0.tar.gz
          ipy -X:Frames -m ensurepip
          ipy -X:Frames -m pip install --no-deps ironpython-pytest.tar.gz
          ipy -X:Frames -m pip install --no-deps typing.tar.gz
          ipy -X:Frames -m pip install --no-deps zipp.tar.gz
          ipy -X:Frames -m pip install --no-deps pyrsistent.tar.gz
          ipy -X:Frames -m pip install --no-deps importlib_metadata.tar.gz
          ipy -X:Frames -m pip install --no-deps functools32.tar.gz
          ipy -X:Frames -m pip install --no-deps attrs.tar.gz
          ipy -X:Frames -m pip install --no-deps jsonschema.tar.gz
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Install dependencies
        run: |
          choco install ironpython --version=2.7.8.1
      - uses: compas-dev/compas-actions.ghpython_components@v1
        with:
          source: src/compas_ghpython/components
          target: src/compas_ghpython/components
      - name: Test import
        run: |
          ipy -m compas
        env:
          IRONPYTHONPATH: ./src
      - name: Run tests
        run: |
          ipy tests/ipy_test_runner.py
        env:
          IRONPYTHONPATH: ./src
