name: publish_yak

on: workflow_dispatch

jobs:

  publish_test_yak:
    runs-on: windows-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Create CPython Grasshopper user objects
      run: |
        invoke build-cpython-ghuser-components

    - name: Create IronPython Grasshopper user objects
      run: |
        choco install ironpython --version=2.7.8.1
        invoke clean
        invoke build-ghuser-components

    - name: Create Rhino7 Yak package
      shell: pwsh
      run: |
        invoke yakerize -m $Env:YAK_TEMPLATE\manifest.yml -l $Env:YAK_TEMPLATE\icon.png -g $Env:USER_OBJECTS -t rh7
      env:
        USER_OBJECTS: src\compas_ghpython\components\ghuser
        YAK_TEMPLATE: src\compas_ghpython\yak_template

    - name: Create Rhino8 Yak package
      shell: pwsh
      run: |
        invoke yakerize -m $Env:YAK_TEMPLATE\manifest.yml -l $Env:YAK_TEMPLATE\icon.png -g $Env:USER_OBJECTS -t rh8
      env:
        USER_OBJECTS: src\compas_ghpython\components_cpython\ghuser
        YAK_TEMPLATE: src\compas_ghpython\yak_template

    - name: Publish to Yak test server (Rhino 7)
      shell: pwsh
      run: |
        $file = Get-ChildItem -Path dist\yak_package\*rh7*.yak -File | Select-Object -ExpandProperty Name
        invoke publish-yak --test-server -y $file
      env:
        YAK_TOKEN: ${{ secrets.YAK_DF_TOKEN }}

    - name: Publish to Yak test server (Rhino 8)
      shell: pwsh
      run: |
        $file = Get-ChildItem -Path dist\yak_package\*rh8*.yak -File | Select-Object -ExpandProperty Name
        invoke publish-yak --test-server -y $file
      env:
        YAK_TOKEN: ${{ secrets.YAK_DF_TOKEN }}
