on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          invoke_test: true
          python: ${{ matrix.python }}
          check_import: true

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v3
        with:
          pypi_token: ${{ secrets.PYPI }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_ghpython_components: true
          gh_source: src/compas_ghpython/components
          gh_target: src/compas_ghpython/components/ghuser
          release_name_prefix: COMPAS
